### ISSUE TITLE
Problem with JSZip 3.0

### ISSUE THREAD

**Issue by vicenteserra** [ozum/pg-structure#14]
Error: This method has been removed in JSZip 3.0, please check the upgrade guide.
    at JSZip.generate (/Users/vicente/Documents/fichador/node_modules/jszip/lib/object.js:311:15)
    at Promise (/Users/vicente/Documents/fichador/node_modules/pg-structure/lib/pg-structure.js:232:30)
    at new Promise (<anonymous>)
    at Function.save (/Users/vicente/Documents/fichador/node_modules/pg-structure/lib/pg-structure.js:225:12)
    at pgStructure.then.db (/Users/vicente/Documents/fichador/seq.js:5:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ozum** [comment]
Thank you for the report.

Error is fixed, please update to latest version.
