### ISSUE TITLE
Column not found pg_constraint.consrc in Postgresql 12

### ISSUE THREAD

**Issue by rapomon** [ozum/pg-structure#31]
This is the error:

```
error: column not found c.consrc
    at Connection.parseE (C:\nodejs\ebm-one\node_modules\pg\lib\connection.js:604:11)
    at Connection.parseMessage (C:\nodejs\ebm-one\node_modules\pg\lib\connection.js:401:19)
    at Socket.<anonymous> (C:\nodejs\ebm-one\node_modules\pg\lib\connection.js:121:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'error',
  length: 261,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'You probably want to refer to column «c.conkey» or «c.conbin».',
  position: '440',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'd:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_relation.c',
  line: '3377',
  routine: 'errorMissingColumn'
}
```

**Comment by rapomon** [comment]
PostgreSQL 12 removes the `pg_constraint.consrc` column. Documentation:

- [PostgreSQL 12](https://www.postgresql.org/docs/12/catalog-pg-constraint.html)
- [PostgreSQL 11](https://www.postgresql.org/docs/11/catalog-pg-constraint.html)

The docs for 11 still include `consrc`, but recommend to use `pg_get_constraintdef`.

**Comment by ozum** [comment]
`pg_get_constraintdef` seems backward compatible with previous versions of PostgreSQL. I fixed the issue. Please check with latest version of `pg-structure`.

**Comment by rapomon** [comment]
Yes! it works fine! Thank you so much!!!

**Comment by ozum** [comment]
You're welcome.
