### ISSUE TITLE
Failure connecting when upgrading from 7.2.1 to 7.2.2

### ISSUE THREAD

**Issue by Qwerios** [ozum/pg-structure#57]
The last working version of pg-structure for me is 7.2.1. I get the following error when connecting with `const db = await pgStructure({...})`:

```
error: function regexp_match(text, unknown) does not exist
    at Parser.parseErrorMessage (/Users/.../node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/Users/.../node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/Users/.../node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (/Users/.../node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 222,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '1395',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '523',
  routine: 'ParseFuncOrColumn'
}
```

The only change between the 2 versions that mentions regexp_match is:
https://github.com/ozum/pg-structure/compare/v7.2.1...v7.2.2#diff-e1e8262918708f757af7937279b07ba0R23

This is a little to deep into your query setup for me to make an assumption on whats happening or how to fix it.

I've tried 7.2.2 with various PG 9.6 databases both local and cloud hosted with not success.
Currently working with 7.2.1 and that's working like a charm 👍

**Comment by Qwerios** [comment]
I found the cause of this issue. The `regexp_match` function only exists in Postgres 10+. Some of my databases are running 9.6 sadly. The `regexp_matches` function is available on both and when I replaced the sql in the sql/9/trigger.sql file it runs fine. Will make a PR for the change.

I cannot get the unit test suite to run since it seems to want to connect to a real local Postgresql database btw

**Comment by ozum** [comment]
Thanks for the PR. I merged and published it.
